#!/usr/bin/env node
/**
 * YouTube Analyzer MCP Server
 * Analyzes video ideas and returns high-performing titles/thumbnails from YouTube
 * Generated by KEN-MCP with production enhancements
 */

// Load environment variables from .env file
import dotenv from 'dotenv';
dotenv.config();

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { setupTools } from './tools.js';
import { setupResources } from './resources.js';
import { setupPrompts } from './prompts.js';

// Production logger - MUST use stderr for MCP servers
const logger = {
  error: (message: string, context?: any) => {
    console.error(`[ERROR] ${new Date().toISOString()} ${message}`, context ? JSON.stringify(context) : '');
  },
  warn: (message: string, context?: any) => {
    console.error(`[WARN] ${new Date().toISOString()} ${message}`, context ? JSON.stringify(context) : '');
  },
  info: (message: string, context?: any) => {
    console.error(`[INFO] ${new Date().toISOString()} ${message}`, context ? JSON.stringify(context) : '');
  }
};

/**
 * Initialize the YouTube Analyzer MCP server with enhanced capabilities
 */
const server = new Server(
  {
    name: 'youtube-analyzer-mcp',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      resources: {},
      prompts: {}
    },
  }
);

/**
 * Configure server components with error handling
 */
try {
  setupTools(server);
  logger.info('Tools configured successfully');
} catch (error) {
  logger.error('Failed to setup tools', {
    error: error instanceof Error ? error.message : String(error),
    stack: error instanceof Error ? error.stack : undefined
  });
  throw error;
}

try {
  setupResources(server);
  logger.info('Resources configured successfully');
} catch (error) {
  logger.error('Failed to setup resources', {
    error: error instanceof Error ? error.message : String(error),
    stack: error instanceof Error ? error.stack : undefined
  });
  throw error;
}

try {
  setupPrompts(server);
  logger.info('Prompts configured successfully');
} catch (error) {
  logger.error('Failed to setup prompts', {
    error: error instanceof Error ? error.message : String(error),
    stack: error instanceof Error ? error.stack : undefined
  });
  throw error;
}


/**
 * Start the YouTube Analyzer MCP server with comprehensive error handling
 */
async function main(): Promise<void> {
  try {
    logger.info('Starting YouTube Analyzer MCP server...');

    const transport = new StdioServerTransport();
    await server.connect(transport);

    logger.info('YouTube Analyzer MCP server started successfully', {
      serverName: 'youtube-analyzer-mcp',
      version: '1.0.0',
      capabilities: ['tools', 'resources', 'prompts']
    });

  } catch (error) {
    logger.error('Failed to start YouTube Analyzer MCP server', {
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      timestamp: new Date().toISOString()
    });
    throw error;
  }
}

// Handle unhandled promise rejections
process.on('unhandledRejection', (reason, promise) => {
  logger.error('Unhandled Promise Rejection', {
    reason: reason instanceof Error ? reason.message : String(reason),
    stack: reason instanceof Error ? reason.stack : undefined,
    promise: promise.toString()
  });
  process.exit(1);
});

// Handle uncaught exceptions
process.on('uncaughtException', (error) => {
  logger.error('Uncaught Exception', {
    error: error.message,
    stack: error.stack,
    timestamp: new Date().toISOString()
  });
  process.exit(1);
});

// Graceful shutdown
process.on('SIGINT', () => {
  logger.info('Received SIGINT, shutting down gracefully...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  logger.info('Received SIGTERM, shutting down gracefully...');
  process.exit(0);
});

// Start the server
main().catch((error) => {
  logger.error('Critical server startup error', {
    error: error instanceof Error ? error.message : String(error),
    stack: error instanceof Error ? error.stack : undefined
  });
  process.exit(1);
});
