#!/usr/bin/env node
/**
 * MCP server for: Create a web scraper MCP server with the following features: 1. **crawl_website** tool: - Crawl w...
 * Generated by KEN-MCP
 */

// Load environment variables from .env file
import dotenv from 'dotenv';
dotenv.config();

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { setupTools } from './tools.js';

// Initialize the MCP server
const server = new Server(
  {
    name: 'feature-mcp',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      resources: {},
      prompts: {},
    },
  }
);

// Set up tools
setupTools(server);

// Start the server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('MCP server started');
}

main().catch(error => {
  console.error('Server error:', error);
  process.exit(1);
});
