version: '3.8'

services:
  pdf-generator-mcp:
    build:
      context: .
      network: host
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
    dns:
      - 8.8.8.8
      - 8.8.4.4
